package DBAccess;

import Models.Appointments;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import utils.DBConnection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.LocalDateTime;

// dbName: WJ07K54

public class DBAppointments {

    public static ObservableList<Appointments> getAllAppts() {
        ObservableList<Appointments> apptList = FXCollections.observableArrayList();

        try {

            // My SQL statement
            String sql = "select * from WJ07K54.appointments;";
            PreparedStatement pStmt = DBConnection.getConnection().prepareStatement(sql);
            ResultSet rs = pStmt.executeQuery();


            while (rs.next()) {
                // getting the data from mySQL
                int appointmentID = rs.getInt("Appointment_ID");  // should be autogenerated
                String title = rs.getString("Title");
                String description = rs.getString("Description");
                String location = rs.getString("Location");
                String type = rs.getString("Type");
                LocalDateTime start = rs.getObject("Start", LocalDateTime.class); // unsure on if this will work found on Stack
                LocalDateTime end = rs.getObject("End", LocalDateTime.class);
                LocalDateTime createDate = rs.getObject("Create_Date", LocalDateTime.class);
                String createdBy = rs.getString("Created_By");
                Timestamp lastUpdate = rs.getTimestamp("Last_Update");
                String lastUpdatedBy = rs.getString("Last_Updated_By");
                int customerID = rs.getInt("Customer_ID");  // should be autogenerated
                int userID = rs.getInt("User_ID");  // should be autogenerated
                int contactID = rs.getInt("Contact_ID"); // should be autogenerated
                Appointments list = new Appointments(appointmentID, title, description, location, type, start, end
                        ,createDate, createdBy,lastUpdate, lastUpdatedBy, customerID, userID, contactID);
                apptList.add(list);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

        return apptList;
    }


}
