package DBAccess;

import Models.Appointments;
import Models.Contacts;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import utils.DBConnection;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.LocalDateTime;

// dbName: WJ07K54

public class DBContacts {

    public static ObservableList<Appointments> getContact(int ID) {
        ObservableList<Appointments> contactAppts = FXCollections.observableArrayList();

        try{
            // mySQL statement
            String sql = "select * from WJ07K54.appointments where Contact_ID = ?;";
            PreparedStatement pstmt = DBConnection.getConnection().prepareStatement(sql);
            pstmt.setInt(1, ID);
            ResultSet rs = pstmt.executeQuery();

            while (rs.next()) {
                int appointmentID = rs.getInt("Appointment_ID");  // should be autogenerated
                String title = rs.getString("Title");
                String description = rs.getString("Description");
                String location = rs.getString("Location");
                String type = rs.getString("Type");
                LocalDateTime start = rs.getObject("Start", LocalDateTime.class); // unsure on if this will work found on Stack
                LocalDateTime end = rs.getObject("End", LocalDateTime.class);
                LocalDateTime createDate = rs.getObject("Create_Date", LocalDateTime.class);
                String createdBy = rs.getString("Created_By");
                Timestamp lastUpdate = rs.getTimestamp("Last_Update");
                String lastUpdatedBy = rs.getString("Last_Updated_By");
                int customerID = rs.getInt("Customer_ID");  // should be autogenerated
                int userID = rs.getInt("User_ID");  // should be autogenerated
                int contactID = rs.getInt("Contact_ID");

                Appointments list = new Appointments(appointmentID, title, description, location, type, start, end
                        ,createDate, createdBy,lastUpdate, lastUpdatedBy, customerID, userID, contactID);

                contactAppts.add(list);
            }

        }
        catch (SQLException e) {
            e.printStackTrace();
        }

        return contactAppts;
    }

}

//Contact_ID int(10) AI PK
//Contact_Name varchar(50)
//Email varchar


//                String name = rs.getString("Contact_Name");
//                String email = rs.getString("Email");
//
//                Contacts list = new Contacts(contactID, name, email);
//                contactList.add(list);
